/**
 * Tests for HTML <-> Markdown conversion
 *
 * These tests verify that:
 * 1. HTML -> Markdown -> HTML roundtrip produces equivalent HTML
 * 2. Various HTML elements are correctly converted
 */

import { htmlToMarkdown } from '../src/utils/html-to-markdown';
import { markdownToHtml } from '../src/utils/markdown-to-html';
import { stripImageSignatures, restoreImageSignatures } from '../src/utils/markdown';

/**
 * Normalize HTML for comparison
 * - Removes heading IDs (Intercom regenerates these)
 * - Normalizes whitespace
 * - Sorts attributes for consistent comparison
 */
function normalizeHtml(html: string): string {
  return html
    // Remove heading IDs (they are auto-generated by Intercom)
    .replace(/ id="h_[a-f0-9]+"/g, '')
    // Remove empty paragraphs
    .replace(/<p[^>]*>\s*<\/p>/g, '')
    // Normalize whitespace
    .replace(/\s+/g, ' ')
    .replace(/>\s+</g, '><')
    .trim();
}

/**
 * Test HTML roundtrip: HTML -> Markdown -> HTML
 * The resulting HTML should be equivalent to the original
 */
function testHtmlRoundtrip(name: string, html: string): { pass: boolean; message: string } {
  const markdown = htmlToMarkdown(html);
  const htmlBack = markdownToHtml(markdown, html);

  const normalizedOriginal = normalizeHtml(html);
  const normalizedResult = normalizeHtml(htmlBack);

  if (normalizedOriginal === normalizedResult) {
    return { pass: true, message: `✓ ${name}` };
  } else {
    return {
      pass: false,
      message: `✗ ${name}\n  Original: ${normalizedOriginal.substring(0, 200)}...\n  Result:   ${normalizedResult.substring(0, 200)}...`,
    };
  }
}

// Test cases
const testCases: { name: string; html: string }[] = [
  {
    name: 'Headings',
    html: '<h1>Title</h1><h2>Subtitle</h2><h3>Section</h3><h4>Subsection</h4>',
  },
  {
    name: 'Text formatting',
    html: '<p class="no-margin"><b>bold</b></p><p class="no-margin"><i>italic</i></p><p class="no-margin"><code>code</code></p>',
  },
  {
    name: 'Bold italic combo',
    html: '<p class="no-margin"><b><i>bold italic</i></b></p>',
  },
  {
    name: 'Links',
    html: '<p class="no-margin"><a href="https://example.com" target="_blank" class="intercom-content-link">link text</a></p>',
  },
  {
    name: 'Lists unordered',
    html: '<ul><li><p class="no-margin">item1</p></li><li><p class="no-margin">item2</p></li></ul>',
  },
  {
    name: 'Lists ordered',
    html: '<ol><li><p class="no-margin">step1</p></li><li><p class="no-margin">step2</p></li></ol>',
  },
  {
    name: 'Images',
    html: '<div class="intercom-container"><img src="https://example.com/image.png"></div>',
  },
  {
    name: 'Horizontal rule',
    html: '<p class="no-margin">before</p><hr><p class="no-margin">after</p>',
  },
  {
    name: 'Code block',
    html: '<pre><code>const x = 1;</code></pre>',
  },
  {
    name: 'Callout gray',
    html: '<div class="intercom-interblocks-callout" style="background-color: #e8e8e880; border-color: #73737633;"><p class="no-margin">note</p></div>',
  },
  {
    name: 'Callout blue',
    html: '<div class="intercom-interblocks-callout" style="background-color: #e3e7fa80; border-color: #334bfa33;"><p class="no-margin">info</p></div>',
  },
  {
    name: 'Callout yellow',
    html: '<div class="intercom-interblocks-callout" style="background-color: #feedaf80; border-color: #fbc91633;"><p class="no-margin">warning</p></div>',
  },
  {
    name: 'Callout red',
    html: '<div class="intercom-interblocks-callout" style="background-color: #fed9db80; border-color: #fd3a5733;"><p class="no-margin">error</p></div>',
  },
  {
    name: 'Callout green',
    html: '<div class="intercom-interblocks-callout" style="background-color: #d7efdc80; border-color: #1bb15733;"><p class="no-margin">success</p></div>',
  },
  {
    name: 'Table',
    html: '<div class="intercom-interblocks-table-container"><table role="presentation"><tbody><tr><td><p class="no-margin">A1</p></td><td><p class="no-margin">B1</p></td></tr><tr><td><p class="no-margin">A2</p></td><td><p class="no-margin">B2</p></td></tr></tbody></table></div>',
  },
  {
    name: 'Text alignment center',
    html: '<p class="intercom-align-center no-margin">centered text</p>',
  },
  {
    name: 'Text alignment right',
    html: '<p class="intercom-align-right no-margin">right aligned</p>',
  },
];

// Combined document test (excluding raw HTML elements like videos, buttons, collapsible sections)
// These elements are kept as raw HTML per design and have known roundtrip limitations
const combinedDocumentHtml = `<h1 id="h_e324f0a1dd">H1</h1><h2 id="h_b3ae805d42">Heading 2</h2><h3 id="h_03290146c3">Heading 3</h3><h4 id="h_9624ce3e6b">Heading 4</h4><p class="no-margin">normal text</p><p class="no-margin"><b>bold</b></p><p class="no-margin"><i>italic</i></p><p class="no-margin"><b><i>bold_italic</i></b></p><p class="no-margin"><code>inline code</code></p><p class="no-margin"><a href="https://example.com/link" target="_blank" class="intercom-content-link">link text</a></p><p class="intercom-align-center no-margin">centered text</p><p class="intercom-align-right no-margin">right aligned</p><div class="intercom-container"><img src="https://example.com/image.png"></div><div class="intercom-interblocks-table-container"><table role="presentation"><tbody><tr><td><p class="no-margin">A1</p></td><td><p class="no-margin">B1</p></td></tr><tr><td><p class="no-margin">A2</p></td><td><p class="no-margin">B2</p></td></tr></tbody></table></div><hr><ul><li><p class="no-margin">list item 1</p></li><li><p class="no-margin">list item 2</p></li></ul><ol><li><p class="no-margin">step 1</p></li><li><p class="no-margin">step 2</p></li></ol><pre><code>code block</code></pre><div class="intercom-interblocks-callout" style="background-color: #e8e8e880; border-color: #73737633;"><p class="no-margin">gray callout</p></div><div class="intercom-interblocks-callout" style="background-color: #e3e7fa80; border-color: #334bfa33;"><p class="no-margin">blue callout</p></div>`;

/**
 * Test image signature stripping and restoration
 */
function testImageSignatures(): { pass: boolean; message: string }[] {
  const results: { pass: boolean; message: string }[] = [];

  // Test 1: Strip signatures from downloads.intercomcdn.com URL
  const signedUrl = 'https://downloads.intercomcdn.com/i/o/925550781/4ee52b3c7f4d2e7215a10b40/image.png?expires=1765159200&signature=753b2c3654455900fc93a8c7f617800bbc0deea9f97bf81c9efef02825060356&req=fSIiE8x%2BmoleFb4f3HP0gNbv081s36DxgbceLLu06bqHDYgKxuHuy7DGFi2b%0AT4k%3D%0A';
  const htmlWithSignedUrl = `<img src="${signedUrl}">`;
  const expectedStripped = '<img src="https://downloads.intercomcdn.com/i/o/925550781/4ee52b3c7f4d2e7215a10b40/image.png">';

  const stripped = stripImageSignatures(htmlWithSignedUrl);
  if (stripped === expectedStripped) {
    results.push({ pass: true, message: '✓ Strip image signatures' });
  } else {
    results.push({
      pass: false,
      message: `✗ Strip image signatures\n  Expected: ${expectedStripped}\n  Got: ${stripped}`,
    });
  }

  // Test 2: Restore signatures
  const restored = restoreImageSignatures(stripped, htmlWithSignedUrl);
  if (restored === htmlWithSignedUrl) {
    results.push({ pass: true, message: '✓ Restore image signatures' });
  } else {
    results.push({
      pass: false,
      message: `✗ Restore image signatures\n  Expected: ${htmlWithSignedUrl}\n  Got: ${restored}`,
    });
  }

  // Test 3: Strip signatures from intercom-attachments URL
  const attachmentUrl = 'https://intercom-attachments-1.com/path/to/file.pdf?expires=123&signature=abc&req=xyz';
  const htmlWithAttachment = `<a href="${attachmentUrl}">file</a>`;
  const strippedAttachment = stripImageSignatures(htmlWithAttachment);
  const expectedAttachmentStripped = '<a href="https://intercom-attachments-1.com/path/to/file.pdf">file</a>';

  if (strippedAttachment === expectedAttachmentStripped) {
    results.push({ pass: true, message: '✓ Strip attachment signatures' });
  } else {
    results.push({
      pass: false,
      message: `✗ Strip attachment signatures\n  Expected: ${expectedAttachmentStripped}\n  Got: ${strippedAttachment}`,
    });
  }

  return results;
}

// Run tests
function runTests(): void {
  console.log('Running HTML roundtrip tests...\n');

  let passed = 0;
  let failed = 0;
  const failures: string[] = [];

  // Run individual element tests
  for (const testCase of testCases) {
    const result = testHtmlRoundtrip(testCase.name, testCase.html);
    if (result.pass) {
      passed++;
      console.log(result.message);
    } else {
      failed++;
      failures.push(result.message);
      console.log(result.message);
    }
  }

  // Run combined document test
  console.log('\nRunning combined document test...');
  const fullDocResult = testHtmlRoundtrip('Combined document', combinedDocumentHtml);
  if (fullDocResult.pass) {
    passed++;
    console.log(fullDocResult.message);
  } else {
    failed++;
    failures.push(fullDocResult.message);
    console.log(fullDocResult.message);
  }

  // Run image signature tests
  console.log('\nRunning image signature tests...');
  const signatureResults = testImageSignatures();
  for (const result of signatureResults) {
    if (result.pass) {
      passed++;
      console.log(result.message);
    } else {
      failed++;
      failures.push(result.message);
      console.log(result.message);
    }
  }

  // Summary
  console.log('\n' + '='.repeat(50));
  console.log(`Results: ${passed} passed, ${failed} failed`);

  if (failed > 0) {
    console.log('\nFailed tests:');
    for (const failure of failures) {
      console.log(failure);
    }
    process.exit(1);
  } else {
    console.log('\nAll tests passed!');
    process.exit(0);
  }
}

runTests();
